disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_filter_count
  - explicit_init
  - first_where
  - modifier_order
  - overridden_super_call
  - private_action
  - redundant_nil_coalescing

excluded:
  - .build
  - Package.swift
  - DerivedData

line_length:
  warning: 120
  error: 200
  ignores_comments: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y
    - to
